# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BCSTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BCSTest
  pod "RxSwift"
  pod "RxCocoa"
  pod "RxAlamofire"
  pod "SnapKit"

  target 'BCSTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BCSTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
